{
    'name': 'Radwan HR Payroll',
    'category': 'Human Resources/Payroll',
    'version': '19.0.1.1',
    'sequence': 1,
    'author': 'Radwan',
    'summary': 'Radwan payroll management for Odoo 19 Community',
    'description': "Radwan payroll management for Odoo 19 Community with localized payroll customizations.",
    'website': 'https://m-radwan.com',
    'license': 'LGPL-3',
    'depends': [
        'mail',
        'hr_holidays',
        'hr_work_entry',
    ],
    'data': [
        'security/hr_payroll_security.xml',
        'security/ir.model.access.csv',
        'data/hr_payroll_sequence.xml',
        'data/hr_payroll_category.xml',
        'data/hr_payroll_data.xml',
        'wizard/hr_payroll_payslips_by_employees_views.xml',
        'views/hr_contract_type_views.xml',
        'views/hr_contract_views.xml',
        'views/hr_salary_rule_views.xml',
        'views/hr_payslip_views.xml',
        'views/hr_employee_views.xml',
        'views/hr_payroll_report.xml',
        'views/hr_work_entry_menus.xml',
        'wizard/hr_payroll_contribution_register_report_views.xml',
        'views/res_config_settings_views.xml',
        'views/report_contribution_register_templates.xml',
        'views/report_payslip_templates.xml',
        'views/report_payslip_details_templates.xml',
        # 'views/hr_contract_history_views.xml',
        'views/hr_leave_type_view.xml',
        'data/mail_template.xml',
    ],
    'images': ['static/description/banner.png'],
    'application': True,
}
